server:
  port: 9011

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

eureka:
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/

  instance:
    leaseRenewalIntervalInSeconds: 10