server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      discovery:
        enabled: true
      server:
        git:
          uri: https://github.com/rcapraro/spring-cloud-sample-config.git